# Generated by Django 3.2 on 2021-12-11 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('cemail', models.EmailField(max_length=254)),
                ('caddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DealerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('demail', models.EmailField(max_length=254)),
                ('dcontact', models.CharField(blank=True, max_length=10, null=True)),
                ('daddress', models.TextField()),
                ('dcompany', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('scontact', models.CharField(blank=True, max_length=10, null=True)),
                ('saddress', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=50)),
                ('vmodel', models.CharField(max_length=50)),
                ('vtype', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler')], max_length=100, null=True)),
                ('vprice', models.FloatField()),
                ('vdescription', models.TextField()),
                ('v_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.dealermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField(default=datetime.date.today)),
                ('tax', models.FloatField()),
                ('payment_mode', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Net Banking', 'Net Banking')], max_length=60, null=True)),
                ('cust_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.customermodel')),
                ('v_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.vehiclemodel')),
            ],
        ),
        migrations.AddField(
            model_name='dealermodel',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.staffmodel'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.staffmodel'),
        ),
    ]
