# Generated by Django 3.2.9 on 2022-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_auto_20220119_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vimage',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
