# Generated by Django 3.2.9 on 2022-01-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_alter_vehiclemodel_vimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='v_id',
            new_name='vehicle_name',
        ),
    ]
